name: Build macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build macOS DMG
        run: npm run build:mac

      - name: Upload macOS Build
        uses: actions/upload-artifact@v3
        with:
          name: my-todo-app-mac
          path: dist/*.dmg
